---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable
  code_climate:
    repo_token:
      secure: "KwB/5i8BJ4EeQUIy6J0YGaYZEsQYi3amHSWzJZ9aXiWV9Bi/qHhX5bXahSbeQsoGiovJ+zaJjMbjd3nBzW5Ugv9M1qlx3G3lQ3DRmSnEsd/oYO65NljeyGhTxfnfwTXVgyCLWZCyP/mtKndKie25yWT9aSh2TafdZCeYDF1Ji0Q="

cache:
  yarn: true

env:
  # we recommend new addons test the current and previous LTS
  # as well as latest stable release (bonus points to beta/canary)
  - EMBER_TRY_SCENARIO=ember-lts-2.8
  - EMBER_TRY_SCENARIO=ember-lts-2.12
  - EMBER_TRY_SCENARIO=ember-release
  - EMBER_TRY_SCENARIO=ember-beta
  - EMBER_TRY_SCENARIO=ember-canary
  - EMBER_TRY_SCENARIO=ember-default

matrix:
  fast_finish: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile --non-interactive

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - COVERAGE=true node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --skip-cleanup

after_script:
  - codeclimate-test-reporter < lcov.dat
